# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Checkout org .github repo
        uses: actions/checkout@v4
        with:
          repository: DINA-community/.github
          path: org-github
      - 
        name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
      
      - name: Merge label YAMLs
        run: |
          yq eval-all ".labels = (.[0].labels + .[1].labels) | {labels: .labels}" \
            org-github/labels/label_default.yaml \
            org-github/labels/label_matcher.yaml \
            > org-github/labels/labels.yml
      
      - name: Debug merged file
        run: |
          ls -la org-github/labels
          cat org-github/labels/label_repospecific.yaml
      
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: org-github/labels/label_repospecific.yaml
